version: '3.8'

services:
  web:
    build: .
    image: <YOUR_DOCKERHUB_USERNAME>/final-project:latest
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=production

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

